### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by tmhn89** [tmhn89/parkman_test#1]
(1) Simple responsive HTML/CSS web page
- [x] Link/Import Bootstrap, Jquery and Google Maps API to your project.
- [x] Use Bootstrap features (grid layout) and CSS to make the site responsive.
- [ ] Use your imagination and creativity with the layout, but keep in mind the simplicity.

(2) Google Maps API
- [x] Import json file
- [x] Load the Google Maps map (with the viewport based on location_data.bounds)
- [x] Draw the zone polygons (location_data.zones.polygon) on top of the map. Use the payment_is_allowed value for deciding the background color of the polygon. 
- [x] Place a draggable marker at your current location given in the data.
- [x] Display other zone information
- [x] Place a start parking button as a part of your layout. Once clicked, the site will tell which zone is being parked.
